### PR TITLE
Improvements and documentation for nginx s2i support

### PR DESCRIPTION
**Pull request by wtrocki**
# Motivation

Added some documentation and s2i improvements to reduce confusion for image endusers. Changed the way source code is fetched to use local context (rather than fixed /tmp path)

# Notes 

It seems that there is no centos version of the image for nginx18. 
Can I create this basing  on changes we done bellow?

### CODE REVIEW

**Comment by wtrocki** [comment]
ping @hhorak

**Comment by hhorak** [comment]
I'm sorry, but rhscl-dockerfiles are no longer actively developed. We now work more actively in specific repositories, e.g. https://github.com/sclorg/nginx-container/.

**Comment by wtrocki** [comment]
@hhorak Thanks for quick response. I would migrate some of the changes to new repo!

**Comment by hhorak** [comment]
OK, thanks.

**Comment by wtrocki** [comment]
Changes were migrated to different repo. Closing

**Pull request closed without merging**
