### PR TITLE
Remove dockerfiles that we don't ship and thus not support

### PR DESCRIPTION
**Pull request by hhorak**
There is no reason to maintain nor generate dockerfiles that nobody really checks and uses. Thus, we shouldn't include them here, otherwise someone may think we support them and would like to use them..

### CODE REVIEW

**Comment by langdon** [comment]
Just a thought, would it be better to just rename them Dockerfile.unsupported or Dockerfile.example? I am not sure, because there are a lot of them to look at, but I wonder if they might be a useful reference for people.

**Comment by hhorak** [comment]
What do you mean by Dockerfile.unsupported?

**Comment by langdon** [comment]
I meant like, instead of deleting them all, rename the files to be something that doesn't immediately work and indicates the status.

**Comment by hhorak** [comment]
Ah, understand now. I'd say we may do it for images that we don't ship now, but we at least know what they should be used for and how. Right now, what is missing here is just `mariadb55`, others sane images are still here. Well, there are some images like `rh-java-common`, which doesn't make sense to provide at all (or at least my imagination is not good enough to think about a valid use case for such an image).

**Pull request merged**
